name = "dashboard-api-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Log to Cloudflare dashboard
[observability]
enabled = true

# KV Namespace Bindings (Example)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
